.icons .sapUiIcon {
  width: 1rem !important;
  height: 1rem !important;
  line-height: 1.2rem !important;
  font-size: 1rem !important;
}

.icons .sapMObjLIconDiv {
  float: left;
  margin-right: 0.5rem;
  width: 1rem;
  height: 1rem;
  text-align: center;
  box-sizing: border-box;
}

.sapMLIB.sapMObjLItem {
  padding: 0.5rem !important;
}

.mainPage .sapMTitleStyleAuto {
  font-size: 1.2rem;
}

.childPage .sapMTitleStyleAuto {
  font-size: 1rem;
}